// Core domain types for Woody

/** Named globe territory (PRD S4). */
export type MapZoneId = 'dm' | 'sp' | 'oc' | 'df'

export interface TrackSourceIds {
  spotify?: string
}

export interface Track {
  /** Internal Woody id; defaults to Spotify catalog id when only Spotify is wired (PRD S7). */
  woodyId?: string
  sources?: TrackSourceIds
  id: string
  name: string
  artist: string
  album: string
  albumArt?: string
  spotifyUri?: string
  youtubeId?: string
  durationMs: number
  previewUrl?: string
}

export interface PersonaLens {
  energy: 'low' | 'medium' | 'high'
  mood: string[]
  exclusions: string[]
  tempo: 'slow' | 'medium' | 'fast'
  era?: string
  texture: string[]
  rawIntent: string
  searchQueries?: string[]
  spotifyGenres?: string[]
  /** Artist names explicitly referenced in the intent (e.g. "Young Nudy meets Tame Impala" -> ["Young Nudy", "Tame Impala"]).
   * Used to seed Last.fm artist-level discovery separately from text search. */
  artistSeeds?: string[]
  /** Artist names from different scenes/eras/regions that are sonically adjacent to the intent territory.
   * Generated by the LLM as a cultural oracle — fills gaps in Last.fm's listening-behavior graph. */
  oracleArtists?: string[]
}

/**
 * Personal taste centroid — weighted mean of acoustic features from tracks the user has played.
 * Updated via exponential moving average on every completed play event.
 * Used to blend the intent-derived acoustic target with the user's demonstrated preferences.
 */
export interface TasteCentroid {
  energy: number
  bpm: number
  /** Spectral centroid normalized 0-1. Starts neutral (0.5) until real acoustic data is available. */
  spectralCentroid: number
  sampleCount: number
  lastUpdated: number
}

export interface TrackAudioAttributes {
  bpm?: number
  energy?: number
  valence?: number
  /** Camelot code e.g. "8B", "3A" */
  key?: string
  /** Short texture tags from LLM (PRD S2). */
  textureTags?: string[]
}

/**
 * Real acoustic feature vector produced by the Woody Acoustic Service (packages/acoustic-service).
 * These are deterministic measurements from actual audio, not LLM estimates.
 * Used for acoustic ranking and personal taste model updates.
 */
export interface AcousticFeatureVector {
  /** Beats per minute */
  bpm: number
  /** RMS energy normalized 0-1 (0=silent, 1=very loud) */
  energy: number
  /** Spectral centroid normalized 0-1 (0=bass-heavy, 1=treble-heavy) */
  spectral_centroid: number
  /** 13 MFCC coefficients (mean over time) — timbral fingerprint */
  mfcc: number[]
  /** Musical key e.g. "C", "F#" */
  key: string
  /** "major" or "minor" */
  mode: 'major' | 'minor'
  /** Camelot wheel notation e.g. "8B", "3A" */
  camelot: string
  /** Mean loudness in dBFS (e.g. -9.4). Negative number; closer to 0 = louder. */
  loudness: number
}

/**
 * Acoustic target derived from PersonaLens for scoring candidates.
 * The acoustic service scores each track against this target.
 *
 * @deprecated Use CLAPEmbedding for navigation. AcousticTarget is the legacy
 * 4-dim proxy and is retained only for the existing /api/intent + globe path.
 * Arc generation never reads this — it operates in 512D CLAP space.
 */
export interface AcousticTarget {
  energy?: number        // 0-1 from lens.energy
  bpmMin?: number        // from lens.tempo
  bpmMax?: number
  valenceProxy?: number  // 0-1 estimated from mood sentiment
  spectralTarget?: number // 0-1 brightness hint from texture words
}

export interface TrackSuggestion {
  track: Track
  reason: string
  tone: 'violet' | 'amber' | 'moss' | 'rose'
  audioAttributes?: TrackAudioAttributes
  /** Map territory for node clustering (PRD S4). */
  zoneId?: MapZoneId
}

export interface RejectedTrack {
  track: Track
  source: 'map' | 'player'
  context: 'suggestion' | 'memory' | 'save_point'
  rejectedAt: Date
  reason?: string
}

export type ListeningContext = 'running' | 'working' | 'exploring' | 'just_listening'

export interface Session {
  id: string
  userId?: string
  intentText: string
  personaLens: PersonaLens
  seedTrack?: Track
  tracks: SessionTrack[]
  mode: 'active' | 'ambient'
  createdAt: Date
  savePoint?: SavePoint
  /** Map track id to accent tone from the last suggestion set. */
  toneByTrackId?: Record<string, TrackSuggestion['tone']>
  /** Legacy lightweight rejection ids kept for backward compatibility. */
  rejectedTrackIds?: string[]
  /** Richer rejection signal for current and future learning flows. */
  rejectedTracks?: RejectedTrack[]
  /** Activity context captured at session start via context intake chips. */
  listeningContext?: ListeningContext
}

export interface SessionTrack {
  track: Track
  position: number
  signal?: 'kept' | 'skipped' | 'shifted' | 'rejected'
  playedAt?: Date
  type: 'anchor' | 'reach' | 'curveball'
  /** Audio estimates captured when the track was recorded into playback history. */
  audioAttributes?: TrackAudioAttributes
}

export interface SavePoint {
  id: string
  name: string
  note?: string
  sessionId: string
  createdAt: Date
  mapPosition?: { x: number; y: number; z: number }
  trackId?: string
  track?: Track
}

export interface MapNode {
  id: string
  trackId: string
  track: Track
  /** x = lat, y = lng on globe (radians); optional z for 3D unit sphere */
  position: { x: number; y: number; z?: number }
  familiarityScore: number
  lastVisited?: Date
  tone: 'violet' | 'amber' | 'moss' | 'rose'
  savePointLabel?: string
}

export interface TasteProfile {
  dominantTones: TrackSuggestion['tone'][]
  commonMoods: string[]
  avgEnergy: 'low' | 'medium' | 'high'
  topArtists: string[]
  sessionCount: number
}

export interface IntentMemoryEntry {
  intentKey: string
  playedTones: TrackSuggestion['tone'][]
  playedEnergies: number[]
  playedBpms?: number[]
  rejectedIds: string[]
  sessionIds: string[]
  updatedAt: string
}

export interface IntentMemory {
  v: 1
  entries: IntentMemoryEntry[]
}

export interface LearnedIntentBias {
  avgEnergy?: number
  avgBpm?: number
  dominantTones?: TrackSuggestion['tone'][]
  excludeTrackIds: string[]
}

// ─── CLAP arc engine types (WOODY_BUILD_SPEC.md Sections 3-5) ───────────────

/** 512-dimensional L2-normalised float array from laion/larger_clap_music_and_speech.
 *  This is the PRIMARY NAVIGATION REPRESENTATION. All arc / k-NN / cold-start
 *  math operates on these vectors. The 5D coords below are display only. */
export type CLAPEmbedding = number[]

/** 5D perceptual projection — display only. Never used as a navigation target. */
export interface AcousticCoords5D {
  energy: number
  warmth: number
  density: number
  organicity: number
  sacred: number
}

export type ArcShape = 'journey' | 'plateau' | 'discharge' | 'peak_early'

/** Single step in a generated arc. */
export interface ArcStep {
  id: string
  positionInArc: number
  progress: number
  transitionDistance: number
  distanceToTarget: number
  isFrissonCandidate: boolean
  waypointDistance: number
  /** 0 = tight coherence; 1-2 = relaxed; 3 = unbounded fallback. */
  relaxationLevel: number
}

/** Arc generation response from POST /api/arc. */
export interface ArcResult {
  steps: ArcStep[]
  arcShape: ArcShape
  reachedTarget: boolean
  finalDistance: number
  coherenceViolations: number
  poolSizeUsed: number
  /** Optional per-step track metadata attached by the Next.js route. */
  trackMap?: Record<string, Track>
  /** Diagnostics for the listen-test failure-mode triage. Not user-facing. */
  diagnostics?: Record<string, unknown>
  latencyMs?: number
}

/** Input to /embed/audio/batch through the AcousticServiceClient. */
export interface EmbedAudioBatchInput {
  id: string
  previewUrl?: string
  artist?: string
  title?: string
}

/** Result of /embed/audio/batch through the AcousticServiceClient. */
export interface EmbedAudioBatchResult {
  id: string
  embedding?: CLAPEmbedding
  audioUrlUsed?: string
  audioSource?: 'preview_url' | 'itunes'
  error?: string
}

// Journey V0 public contracts

export type AttributionProvenance =
  | 'user_text'
  | 'model_suggested'
  | 'user_confirmed'
  | 'behavior_observed'
  | 'system_inferred'

export type JourneyPhaseType = 'settle' | 'build' | 'sustain' | 'impact' | 'release'
export type Knownness = 'known_track' | 'known_artist' | 'unseen'
export type JourneySessionMode = 'adaptive' | 'control_observation'

export type JourneyTagCategory =
  | 'function'
  | 'movement'
  | 'rhythm'
  | 'texture'
  | 'impact'
  | 'relationship'

export interface JourneyAttribution {
  field: string
  value: string
  source: AttributionProvenance
  recordedAt: string
}

export interface JourneyAnchor {
  track: Track
  role: 'opener' | 'reference'
  note: string
  suggestedTags: Partial<Record<JourneyTagCategory, string[]>>
  confirmedTags: Partial<Record<JourneyTagCategory, string[]>>
  attribution: JourneyAttribution[]
}

export interface JourneyPhase {
  id: string
  type: JourneyPhaseType
  label: string
  description: string
  startMinute: number
  endMinute: number
  accepted: boolean
}

export interface JourneyImpactWindow {
  id: string
  minute: number
  enabled: boolean
  description: string
}

export interface JourneyPlanV1 {
  version: 1
  sessionId: string
  mode: JourneySessionMode
  activity: 'running'
  intent: string
  durationMinutes: number
  phases: JourneyPhase[]
  familiarityTarget: number
  impactWindows: JourneyImpactWindow[]
  anchors: JourneyAnchor[]
  attribution: JourneyAttribution[]
  createdAt: string
}

export interface JourneyTransitionDiagnostics {
  transitionDistance: number
  targetDistance: number
  familiarityFit: number
  skipPenalty: number
  relaxationLevel: number
  candidateCount: number
  latencyMs: number
}

export interface JourneyDecision {
  decisionId: string
  selectedTrack: Track
  phase: JourneyPhaseType
  knownness: Knownness
  confidence: number
  diagnostics: JourneyTransitionDiagnostics
}

export type JourneyEventType =
  | 'session_started'
  | 'track_started'
  | 'track_completed'
  | 'manual_transition'
  | 'user_override'
  | 'queue_added'
  | 'queue_paused'
  | 'session_ended'
  | 'explicit_approval'
  | 'explicit_rejection'
  | 'wake_lock_lost'
  | 'network_error'

export interface JourneyEventV1 {
  version: 1
  timestamp: string
  eventType: JourneyEventType
  track?: Track
  rawPositionMs?: number
  rawDurationMs?: number
  listenedFraction?: number
  initiatingSource: 'woody' | 'user' | 'spotify' | 'system'
  decisionId?: string
  attribution?: JourneyAttribution
}

export interface JourneySkipPenalty {
  trackId: string
  weight: number
  decisionsRemaining: number
}

export interface JourneySessionV1 {
  version: 1
  plan: JourneyPlanV1
  status: 'planned' | 'active' | 'paused_override' | 'completed'
  decisions: JourneyDecision[]
  events: JourneyEventV1[]
  playedTrackIds: string[]
  rejectedTrackIds: string[]
  skipPenalties: JourneySkipPenalty[]
  startedAt?: string
  endedAt?: string
  review?: JourneyRunReview
}

export interface JourneyRunReview {
  pairNumber: 1 | 2 | 3 | 4
  pairLeg: 1 | 2
  timingSupport: number
  manualManagementEffort: number
  sustainedEffortSupport: number
  impactMoments: string
  mistimedTransitions: string
  overallPreference: 'adaptive' | 'control_observation' | 'no_preference'
  chooseAdaptiveAgain: boolean
  submittedAt: string
}
