// Core domain types for Woody

/** Named globe territory (PRD S4). */
export type MapZoneId = 'dm' | 'sp' | 'oc' | 'df'

export interface TrackSourceIds {
  spotify?: string
}

export interface Track {
  /** Internal Woody id; defaults to Spotify catalog id when only Spotify is wired (PRD S7). */
  woodyId?: string
  sources?: TrackSourceIds
  id: string
  name: string
  artist: string
  album: string
  albumArt?: string
  spotifyUri?: string
  youtubeId?: string
  durationMs: number
  previewUrl?: string
}

export interface PersonaLens {
  energy: 'low' | 'medium' | 'high'
  mood: string[]
  exclusions: string[]
  tempo: 'slow' | 'medium' | 'fast'
  era?: string
  texture: string[]
  rawIntent: string
  searchQueries?: string[]
  spotifyGenres?: string[]
  /** Artist names explicitly referenced in the intent (e.g. "Young Nudy meets Tame Impala" -> ["Young Nudy", "Tame Impala"]).
   * Used to seed Last.fm artist-level discovery separately from text search. */
  artistSeeds?: string[]
  /** Artist names from different scenes/eras/regions that are sonically adjacent to the intent territory.
   * Generated by the LLM as a cultural oracle — fills gaps in Last.fm's listening-behavior graph. */
  oracleArtists?: string[]
}

/**
 * Personal taste centroid — weighted mean of acoustic features from tracks the user has played.
 * Updated via exponential moving average on every completed play event.
 * Used to blend the intent-derived acoustic target with the user's demonstrated preferences.
 */
export interface TasteCentroid {
  energy: number
  bpm: number
  /** Spectral centroid normalized 0-1. Starts neutral (0.5) until real acoustic data is available. */
  spectralCentroid: number
  sampleCount: number
  lastUpdated: number
}

export interface TrackAudioAttributes {
  bpm?: number
  energy?: number
  valence?: number
  /** Camelot code e.g. "8B", "3A" */
  key?: string
  /** Short texture tags from LLM (PRD S2). */
  textureTags?: string[]
}

/**
 * Real acoustic feature vector produced by the Woody Acoustic Service (packages/acoustic-service).
 * These are deterministic measurements from actual audio, not LLM estimates.
 * Used for acoustic ranking and personal taste model updates.
 */
export interface AcousticFeatureVector {
  /** Beats per minute */
  bpm: number
  /** RMS energy normalized 0-1 (0=silent, 1=very loud) */
  energy: number
  /** Spectral centroid normalized 0-1 (0=bass-heavy, 1=treble-heavy) */
  spectral_centroid: number
  /** 13 MFCC coefficients (mean over time) — timbral fingerprint */
  mfcc: number[]
  /** Musical key e.g. "C", "F#" */
  key: string
  /** "major" or "minor" */
  mode: 'major' | 'minor'
  /** Camelot wheel notation e.g. "8B", "3A" */
  camelot: string
  /** Mean loudness in dBFS (e.g. -9.4). Negative number; closer to 0 = louder. */
  loudness: number
}

/**
 * Acoustic target derived from PersonaLens for scoring candidates.
 * The acoustic service scores each track against this target.
 */
export interface AcousticTarget {
  energy?: number        // 0-1 from lens.energy
  bpmMin?: number        // from lens.tempo
  bpmMax?: number
  valenceProxy?: number  // 0-1 estimated from mood sentiment
  spectralTarget?: number // 0-1 brightness hint from texture words
}

export interface TrackSuggestion {
  track: Track
  reason: string
  tone: 'violet' | 'amber' | 'moss' | 'rose'
  audioAttributes?: TrackAudioAttributes
  /** Map territory for node clustering (PRD S4). */
  zoneId?: MapZoneId
}

export interface RejectedTrack {
  track: Track
  source: 'map' | 'player'
  context: 'suggestion' | 'memory' | 'save_point'
  rejectedAt: Date
  reason?: string
}

export type ListeningContext = 'running' | 'working' | 'exploring' | 'just_listening'

export interface Session {
  id: string
  userId?: string
  intentText: string
  personaLens: PersonaLens
  seedTrack?: Track
  tracks: SessionTrack[]
  mode: 'active' | 'ambient'
  createdAt: Date
  savePoint?: SavePoint
  /** Map track id to accent tone from the last suggestion set. */
  toneByTrackId?: Record<string, TrackSuggestion['tone']>
  /** Legacy lightweight rejection ids kept for backward compatibility. */
  rejectedTrackIds?: string[]
  /** Richer rejection signal for current and future learning flows. */
  rejectedTracks?: RejectedTrack[]
  /** Activity context captured at session start via context intake chips. */
  listeningContext?: ListeningContext
}

export interface SessionTrack {
  track: Track
  position: number
  signal?: 'kept' | 'skipped' | 'shifted' | 'rejected'
  playedAt?: Date
  type: 'anchor' | 'reach' | 'curveball'
  /** Audio estimates captured when the track was recorded into playback history. */
  audioAttributes?: TrackAudioAttributes
}

export interface SavePoint {
  id: string
  name: string
  note?: string
  sessionId: string
  createdAt: Date
  mapPosition?: { x: number; y: number; z: number }
  trackId?: string
  track?: Track
}

export interface MapNode {
  id: string
  trackId: string
  track: Track
  /** x = lat, y = lng on globe (radians); optional z for 3D unit sphere */
  position: { x: number; y: number; z?: number }
  familiarityScore: number
  lastVisited?: Date
  tone: 'violet' | 'amber' | 'moss' | 'rose'
  savePointLabel?: string
}

export interface TasteProfile {
  dominantTones: TrackSuggestion['tone'][]
  commonMoods: string[]
  avgEnergy: 'low' | 'medium' | 'high'
  topArtists: string[]
  sessionCount: number
}

export interface IntentMemoryEntry {
  intentKey: string
  playedTones: TrackSuggestion['tone'][]
  playedEnergies: number[]
  playedBpms?: number[]
  rejectedIds: string[]
  sessionIds: string[]
  updatedAt: string
}

export interface IntentMemory {
  v: 1
  entries: IntentMemoryEntry[]
}

export interface LearnedIntentBias {
  avgEnergy?: number
  avgBpm?: number
  dominantTones?: TrackSuggestion['tone'][]
  excludeTrackIds: string[]
}
